{{- if .Values.acmeEmail -}}
{{- if .Values.defaultIngressSubdomain -}}
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-prod-route53-secret
data:
  secretKey: {{ .Values.certManagerRoute53.secretAccessKey | required ".Values.certManagerRoute53.secretAccessKey is required if acmeEmail is set" | b64enc | quote }}
{{- end -}}
{{- end -}}
