{{- if .Values.util.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: util
  labels:
    app: util
spec:
  replicas: 1
  selector:
    matchLabels:
      app: util
  template:
    metadata:
      labels:
        app: util
    spec:
      containers:
        - name: util
          image: alpine
          command: ["/bin/sh", "-c"]
          args: ["sleep 1000000"]
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
{{- end -}}
