repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io

helmDefaults:
  verify: true
  wait: true
  timeout: 300
  recreatePods: true
  force: false

helmfiles:
  - "helmfiles/*/helmfile.yaml"
