apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  internal.override: |+
    template IN ANY . {
      match "^(.*)\.{{ .Values.defaultIngressSubdomain | replace "." "\\." }}\.$"
      answer "{{"{{"}} .Name {{"}}"}} 60 IN CNAME ingress-nginx-controller.ingress-nginx.svc.cluster.local."
      upstream 127.0.0.1:53
      fallthrough
    }
