{{- if .Values.echo.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: echo
  labels:
    app: echo
spec:
  type: ClusterIP
  selector:
    app: echo
  ports:
    - port: 8080
      targetPort: 8080
{{- end -}}
